### ISSUE TITLE
Use WP-CLI

### ISSUE THREAD

**Issue by rahul286** [medhanu/wordpress-script#10]
Please check - https://github.com/medhanu/wordpress-script/blob/master/buildsite.sh#L69

Using WP-CLI can cut down your efforts. 

Please move all WordPress related part to https://wp-cli.org/

When you are done close this issue via Github commit.

**Comment by medhanu** [comment]
Hi Rahul,
Thanks for your suggestion, wp-cli helped a lot to reduce the complexity of script.
I have used wp-cli in script to setup and configure all wordpress related tasks.
 Kindly review.

Best Regard,
Dhananjay

**Comment by rahul286** [comment]
Can you please paste link to relevant commits so I can review code changes?

**Comment by medhanu** [comment]
Hi Rahul,

I have merged all code in main.sh.

Please check below link,
https://github.com/medhanu/wordpress-script/blob/master/main.sh#L285


Regards,
Dhananjay
